### ISSUE TITLE
[event timeline] observation date sometimes does not appear

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#127] opened 2016-06-27 19:11 UTC
Sometimes when zooming out, the observation date indicator line does not appear - see below.

![screen shot 2016-06-27 at 2 52 13 pm](https://cloud.githubusercontent.com/assets/983575/16392326/5d86257c-3c79-11e6-9e9e-88e825edce69.png)

![screen shot 2016-06-27 at 2 52 38 pm](https://cloud.githubusercontent.com/assets/983575/16392318/51f485a0-3c79-11e6-9f47-c085cc676561.png)

**Comment by ddialer** [comment] 2016-07-14 16:47
Can't reproduce. Probably was fixed with one of the previous issues.

**Closed as completed** 2016-07-27 20:58 UTC
Labels: bug?, wontfix, not consistently reproducible, Timeline: features and events, 3.1beta
