### ISSUE TITLE
LASCO is not updating

### ISSUE THREAD

**Issue by wireeye** [Helioviewer-Project/helioviewer.org#489] opened 2023-09-14 20:55 UTC
Greetings, I have noticed since Sept. 12th that LASCO hasn't updated from the Sept. 11th, date. I didn't know if this issue had been reported as yet. 
Thanks for your time in advance. 
wireeye

**Comment by wafels** [comment] 2023-09-15 16:10
Thanks for the bug report.

This was ultimately caused by a syntax error in the code that creates the JPEG2000 files. The bug affected LASCO, EIT and STEREO-A data. It's been fixed now, and more recent LASCO data has started appearing again.

**Closed as completed** 2023-09-15 16:10 UTC
