### ISSUE TITLE
Field of view recenters when loading using jump

### ISSUE THREAD

**Issue by ehsteve** [Helioviewer-Project/helioviewer.org#158] opened 2016-09-02 19:07 UTC
If zoomed in on a specific event, using the jump button to see how it evolves will recenter the field of the view (though not the zoom level) to the center of the Sun. This seems to only happen if it needs to load new data. If the data has already been cached it works fine.

**Comment by wafels** [comment] 2016-09-02 20:19
I am unable to reproduce this issue on Firefox 48.0.1 or Chrome Version 52.0.2743.116 (64-bit).  Which browser are you using, and is this reported behavior associated with a particular time or event?

**Comment by ehsteve** [comment] 2016-10-18 14:27
Safari and no.

**Comment by wafels** [comment] 2016-10-18 14:57
Confirmed.

**Comment by wafels** [comment] 2016-11-08 22:46
Seems to be fixed perhaps by a Safari update, or not reproducible at the moment.  Closing since not reproducible,

**Closed as completed by wafels** 2016-11-08 22:46 UTC
Labels: bug?, priority: high, browser: Safari, 3.1, not consistently reproducible
