### ISSUE TITLE
Again video flow is with gap.

### ISSUE THREAD

**Issue by Anthrwpos** [Helioviewer-Project/helioviewer.org#330] opened 2022-01-29 18:19 UTC
Hi, again video [flow ](https://helioviewer.org/?movieId=MNDN5)is with gap.

**Comment by dgarciabriseno** [comment] 2022-01-31 15:39
Working on this today.

**Comment by dgarciabriseno** [comment] 2022-02-02 17:12
Sorry this took a while. It should be resolved over the next few days as new data comes in on helioviewer.org. The problem is with the available space we have remaining on helioviewer.org means we need to limit how much data we pull in. But there has been an issue with our scripts causing the gaps. I patched it before, but then had too much data coming in so I needed to revert that change. I applied a new patch this morning which I am hoping will resolve this.

**Comment by Anthrwpos** [comment] 2022-02-04 18:56
Hi, still with gaps. Thanks

**Comment by dgarciabriseno** [comment] 2022-02-15 18:51
A new patch was implemented on Feb 6, is the image data available between Feb 6 and now still skipping the way it was before?

**Comment by Anthrwpos** [comment] 2022-02-16 21:40
Hi, sorry, now i saw your reply. Yes, as i saw it today, it skips almost 30 mins in SDO AIA.

**Comment by dgarciabriseno** [comment] 2022-02-17 20:00
At this time images from SDO on helioviewer are expected to be approximately 30 minutes apart. We're in the process of migrating to a new server where we'll be able to pull in data that's closer together.

**Comment by dgarciabriseno** [comment] 2023-02-09 18:09
This was due to server things back in early 2022. Closing.

**Closed as completed by dgarciabriseno** 2023-02-09 18:09 UTC
